import { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/layouts/PageLayout.module.scss";

interface IProps {
  title: string;
  description?: string;
  children: React.ReactNode;
}
const Index: NextPage<IProps> = ({ title, description, children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {children}
      </main>
    </div>
  );
};
export default Index;
