export const roadmap = [
  {
    type: "BI",
    month: "9-сар",
    day: "01",
    year: "2021",
    title: " Bar Chart",
    description: " Өгөгдлийг баганан байдлаар дүрслэнэ",
    item: ["Untitled.png", "Screenshot.png", "Untitled.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "03",
    year: "2021",
    title: " Line chart",
    description: " Өгөгдлийг шугаман байдлаар дүрслэнэ",
    item: ["Untitled.png", "Screenshot.png", "Untitled.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "05",
    year: "2021",
    title: "Pie chart",
    description: "Өгөгдлийг бялуун байдлаар дүрслэнэ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: "Gauge chart",
    description: "Үйл ажиллагааны биелэлтийг хянах зориулалттай",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "07",
    year: "2021",
    title: " Big number chart",
    description: "KPI тоо харуулна",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-cap",
    day: "08",
    year: "2021",
    title: " Tree Map chart",
    description: "Өгөгдлийг мод бүтэцтэй байдлаар харуулна",
    // item:['head-the-dummy-avatar-man-tie-72756.png'],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "09",
    year: "2022",
    title: " Table, Pivot",
    description: "Өгөгдлийг хүснэгтэн байдлаар болон pivot хүснэгтээр харна",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "12-сар",
    day: "15",
    year: "2021",
    title: "Bar chart stacked",
    description: "Баганан чарт дээр 2 өөр утгатай график давхарлаж харуулна",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Chart Config",
  },
  {
    type: "BI",
    month: "12-сар",
    day: "17",
    year: "2021",
    title: "Chart title size",
    description: "Өгөгдлийн чарт дээрх гарчигны хэмжээг өөрчлөх",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Chart Config",
  },
  {
    type: "BI",
    month: "5-сар",
    day: "01",
    year: "2022",
    title: "Worksheet design renewal ",
    description: "Шинэ загвар бүхий Worksheet  хэсгийн Version2 гарж ирэхнээ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "5-сар",
    day: "17",
    year: "2022",
    title: "eSchool",
    description:
      "eSchool буюу education чиглэлээр үйлчилгээ үзүүлж байгаа компанитай хамтрах",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Integration",
  },
  {
    type: "BI",
    month: "6-сар",
    day: "20",
    year: "2022",
    title: "Calculated Field",
    description:
      " Өөрийн дурын тооцооллыг чарт болон дашборд дээр оруулах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: "Work Sheet chart – уудыг дурын байдлаар зохиомжлох",
    description:
      "Өөрийн хүссэн байрлалд оруулж хэмжээг ихэсгэж багасгаж байрлуулах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: " Зураг, Текст, Видео оруулах",
    description: "Шинэ component оруулдаг болсон",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: " Дэвсгэр өнгө болон Chart – уудын өнгөний нийлэмж сонгох",
    description: "Theme сонгодог",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: " Эрх бүхий хэрэглэгч dashboard – г share хийх",
    description: "User shar",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title: "Import Excel",
    description: "Та өөрийн excel файлыг оруулах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Import Data",
  },
  {
    type: "BI",
    month: "6-сар",
    day: "20",
    year: "2022",
    title: "Import CSV",
    description: "Та өөрийн CSV  файлыг оруулах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Import Data",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "03",
    year: "2022",
    title: "Import JSON",
    description: "Та өөрийн JSON файлыг оруулах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Import Data",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "01",
    year: "2021",
    title: "Connect 252 data warehouse",
    description: "Та манай санал болгосон Warehouse тэй холбогдоно",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Data Source",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "01",
    year: "2021",
    title: "Save data source by relationship",
    description:
      "Өгөгдлийн эх үүсвэрээ хооронд нь join хийсэн байдлаар чартууддаа ашиглах боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Data Source",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "20",
    year: "2022",
    title: "Connect any data source ",
    description: "Дурын өгөгдлийн сантайгаа холбогдож болно",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Data Source",
  },
  {
    type: "BI",
    month: "6-сар",
    day: "20",
    year: "2022",
    title: "Able",
    description: "Able компанитай хамтын ажиллагаа",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Integration",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "eClinic",
    description: "eClinic компанитай хамтын ажиллагаа",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Integration",
  },
  {
    type: "BI",
    month: "6-сар",
    day: "20",
    year: "2022",
    title: "iMap",
    description: "iMap компанитай хамтын ажиллагаа",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Integration",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "New additional Tooltips",
    description:
      "Та дурын өөрийн брэнд өнгөө ч гэсэн сонголтоор оруулж чарт дашбордны өнгөө өөрчлөх боломжтой",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Chart Config",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "Float , Unfloat",
    description:
      "Dashboard дээрх item нууд хатуу болон хөвөлттэй байдлаар байршиж болохнээ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "06",
    year: "2021",
    title:
      "Холбоо хамаарал бүхий chart – уудыг нэгдсэн байдлаар хайж шүүлж хийх",
    description: "Филтер",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "Export as CSV",
    description: "Хийсэн чартынхаа өгөгдлийг CSV болгож авах",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "In Process",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "Export as PDF",
    description: "Хийсэн чарт болон дашбордоо PDF болгож авах",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "8-сар",
    day: "20",
    year: "2022",
    title: "Slicer",
    description: "Дундын филтер маягийн чарт",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "10-сар",
    day: "20",
    year: "2022",
    title: "Heatmap",
    description: "Heatmap ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "10-сар",
    day: "20",
    year: "2022",
    title: "Scatter",
    description: "Тархалтын график",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "10-сар",
    day: "20",
    year: "2022",
    title: "Sankey",
    description: "Хамаарлын график",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "11-сар",
    day: "20",
    year: "2022",
    title: "Forecasting function",
    description: "Машин сургалтын загвар ашиглан таамаглах нь",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Worksheet",
  },
  {
    type: "BI",
    month: "7-сар",
    day: "10",
    year: "2022",
    title: "Cross Filter by chart",
    description: "Та чартуудаараа чартаа филтердэж болно",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Dashboard",
  },
  {
    type: "BI",
    month: "7-сар",
    day: "10",
    year: "2022",
    title: "New additional Tooltips",
    description: "Tooltips дээр агуулагдаж буй мэдээлэл нэмэгдлээ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Chart Config",
  },
  {
    type: "BI",
    month: "9-сар",
    day: "30",
    year: "2022",
    title: "Mobile application",
    description: "Утасны хувилбар",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "BI",
  },
  {
    type: "BI",
    month: "7-сар",
    day: "10",
    year: "2022",
    title: "Add aliases",
    description: "Өгөгдлөө чартан дээрээсээ нэрийг нь өөрчлөж болохнээ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "Data Source",
  },
  {
    type: "ETL",
    month: "7-сар",
    day: "10",
    year: "2022",
    title: "Add aliases",
    description: "Өгөгдлөө чартан дээрээсээ нэрийг нь өөрчлөж болохнээ",
    item: ["Screenshot.png", "Screenshot.png", "Screenshot.png"],
    activity: "Not Completed",
    category: "ETL1",
  },
];
